Repository reanahub/reana, pull requests merged in 2018-04, with the labels that each got.

#54 docs: unification of release note links
  docs/components.rst
Labels: Status: in review

#57 docs: general update for v0.2.0 release
  README.rst
  docs/administratorguide.rst
  docs/architecture.rst
  docs/components.rst
  docs/concepts.rst
  docs/examples.rst
  docs/gettingstarted.rst
  docs/index.rst
  docs/userguide.rst
Labels: Need: work

#58 release: v0.2.0
  AUTHORS.rst
  CHANGES.rst
  reana/version.py
Labels: Need: work, Status: in review

#59 fix mrc's email address
  AUTHORS.rst
Labels: Status: in review
