Repository reanahub/reana, pull requests merged in 2019-10, with the labels that each got.

#206 make: pin Kubernetes version to 1.15.4
  Makefile
Labels: deployment

#207 make: fail if cannot connect to Minikube
  Makefile
Labels: deployment/cern

#214 cli: new CDCI INTEGRAL examples
  reana/cli.py
Labels: community/cdci

#215 cli: add option to output built image tags
  reana/cli.py
Labels: deployment/cern
